### ISSUE TITLE
user-can-search-for-anime

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/anirate#1]
## 📐 Functionality

User can see and use the search bar by typing in an anime name.

## 🖼️ Wireframe
![user can search for anime mobile](https://user-images.githubusercontent.com/99566488/164063047-78fd8fcc-1d5d-4757-80fa-7f33ec37d6b5.png)
![user can search for anime desktop](https://user-images.githubusercontent.com/99566488/164063131-d86cb9ba-517f-4080-b1da-be5e139666b0.png)
![user can search for anime desktop - 2](https://user-images.githubusercontent.com/99566488/164063138-55e2cea4-812c-4753-a33b-b031f7467390.png)

## ✅ Task List

- [x] Create a form with a search input 
- [x] Ensure that the form looks nice on both desktop and mobile screens
- [x] Make all inputs required 
- [x] Create a data model to hold the current search query 
- [x] Listen for a submit event on the form 
- [x] Store the search string in the data model
- [x] Access the API
- [x] Search the API for the search input
- [x] Return the top 6 results 
- [x] Check the console to confirm the request was successful
