### ISSUE TITLE
user-can-view-anime-search-results

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/anirate#2]
## 📐 Functionality
The user will be able to view the top 6 results that match the anime name they searched for

## 🖼️ Wireframes

![user can view anime search results mobile](https://user-images.githubusercontent.com/99566488/164062559-4bbbf303-855d-42eb-9e9f-4eb90afefde7.png)
![user can view anime search results Desktop](https://user-images.githubusercontent.com/99566488/164062617-ad218f89-05ff-4e2c-95c5-340808c433f8.png)

## ✅ Task List

- [x] Add a property to the data model to hold the search results
- [x] Ensure the search results are stored when the user hits submit
- [x] Verify search results are saved to local storage along with the rest of the data model on page reload
- [x] Add a div[data-view="search"] to the HTML
- [x] Add an empty unordered list to the `div[data-view="search"]` element in the HTML
- [x] Add some dummy search results to the unordered list in the HTML and style them to match the wireframe
- [x] Check that the results list looks good on both mobile and desktop screens
- [x] Define a function that takes a single search result object and returns a DOM tree that matches one of the example 
       entries in the HTML
- [x] Use a loop to create a DOM tree for each search result in the data model and append it to the page when the 
     `'DOMContentLoaded'` event is fired
- [x] Remove the example HTML search results once the search results are successfully being appended to the DOM on page 
       load
- [x] Ensure that submitting a new search also creates a new DOM tree for it and adds it to the page, replacing previous 
       searches
- [x] Ensure that submitting a new search automatically shows the search results without reloading the page
- [x] Ensure that refreshing the pages shows the same search results as before refreshing
- [x] Clean up all unnecessary styling
- [x] Test the app some more in a private browsing tab
- [x] Fix all errors
