### ISSUE TITLE
user-can-create-a-review

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/anirate#3]
## 📐 Functionality
The user can create a review based on a specific anime selected from the search results. 

## 🖼️ Wireframes
![Screen Shot 2022-04-21 at 1 00 18 PM](https://user-images.githubusercontent.com/99566488/164544265-4b15569d-3268-4853-b403-361a7b2e4e85.png)
![Screen Shot 2022-04-21 at 1 06 54 PM](https://user-images.githubusercontent.com/99566488/164544284-755a9503-5def-4ff5-be41-4f9afcac0a41.png)
![Screen Shot 2022-04-21 at 1 00 49 PM](https://user-images.githubusercontent.com/99566488/164544290-f8dc6f30-be5a-461f-bda5-7aeba8e7ff9f.png)

## ✅ Task List

- [x] Add a `div[data-view="review-form"]` to the HTML.
- [x] Add a form for creating a new review to the `div[data-view="review-form"]`.
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Make all inputs of the review form `required`.
- [x] Listen for `'submit'` events on the review form and:
  - [x] Put the form's input values into a new object.
  - [x] Add the `nextReviewId` to the object.
  - [x] Increment the `nextReviewId` on the data model.
  - [x] Prepend the new object to the reviews in the data model.
  - [x] Reset the form inputs.
- [x] Verify that new reviews are saved to local storage along with the rest of the data model on page reload.
- [x] Verify that each new review receives an incrementing `entryId`.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
