### ISSUE TITLE
user-can-view-their-reviews

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/anirate#4]
## 📐 Functionality
The user will be able to view each of their reviews via navigation link. They will also be directed to their reviews pages immediately after creating a new review.

## 🖼️ Wireframes
![Screen Shot 2022-04-22 at 2 45 55 PM](https://user-images.githubusercontent.com/99566488/164800349-be2c80bb-efe4-4903-bd3d-eb166efa140e.png)

![Screen Shot 2022-04-22 at 2 45 24 PM](https://user-images.githubusercontent.com/99566488/164800402-7ce17029-f52d-4836-b2f2-063ff2d8e9e9.png)

## ✅ Task List

- [x] Add a sibling `div[data-view="review"]` to the HTML.
- [x] Add an empty unordered list to the `div[data-view="review"]` element in the HTML.
- [x] Add some dummy reviews to the unordered list in the HTML and style them to match the wireframe.
- [x] Check that the entries list looks good on both mobile and desktop screens.
- [x] Define a function that takes a single review object and returns a DOM tree that matches one of the example entries in the HTML.
- [x] Use a loop to create a DOM tree for each journal entry in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [x] Remove the example HTML entries once the user's entries are successfully being appended to the DOM on page load.
- [x] Add a navigation item to the navbar for Search and Reviews (desktop).
- [x] Add a navigation icon to the footer navbar for Search and Reviews (mobile).
- [x] Add an anchor to the search and reviews view that shows their respective pages.
- [x] Ensure that submitting a new journal entry also creates a new DOM tree for it and adds it to the page.
- [x] Ensure that submitting a new journal entry automatically shows the `'entries'` view without reloading the page.
- [x] Ensure that refreshing the pages shows the same view as before refreshing.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
