### ISSUE TITLE
user-can-edit-their-reviews

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/anirate#5]
## 📐 Functionality
The user can edit their reviews (via the review page) by clicking the edit pen icon. The user can save their changes, which will be updated immediately.

## 🖼️ Wireframes
![Screen Shot 2022-04-25 at 10 14 48 AM](https://user-images.githubusercontent.com/99566488/165172961-9fe01bf0-c248-4c62-9b43-aa03dd2927a0.png)
![Screen Shot 2022-04-25 at 10 14 18 AM](https://user-images.githubusercontent.com/99566488/165172982-b0f88536-1e54-4aaa-99cb-02e943665b03.png)
![Screen Shot 2022-04-25 at 10 14 26 AM](https://user-images.githubusercontent.com/99566488/165172997-664fb225-1963-4597-aa67-ddc54ec70b86.png)

## ✅ Task List

- [x] Update review rendering function to include an edit icon for each rendered entry.
- [x] Ensure that each rendered review is given a `data-entry-id` attribute indicating which entry it is.
- [x] Listen for clicks on the parent element of all rendered entries.
- [x] Show the entry form if an edit icon was clicked.
- [x] Find the matching review object in the data model and assign it to the data model's `editing` property if an edit icon was clicked.
- [x] Pre-populate the review form with the clicked entry's values from the object found in the data model.
- [x] Update the review form's submit handler function to conditionally add a new entry object or update the existing one.
- [x] Update the review form's submit handler function to conditionally add a new entry DOM tree or replace the existing one.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
